# Generated by Django 4.2.1 on 2023-07-12 17:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='created_at',
            field=models.DateTimeField(auto_now=True, verbose_name='작성일'),
        ),
        migrations.AddField(
            model_name='post',
            name='like_count',
            field=models.IntegerField(null=True, verbose_name='좋아요개수'),
        ),
        migrations.AddField(
            model_name='post',
            name='likes',
            field=models.ManyToManyField(related_name='likes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.TextField(verbose_name='상세일정'),
        ),
        migrations.AlterField(
            model_name='post',
            name='destination',
            field=models.CharField(max_length=20, verbose_name='여행지'),
        ),
        migrations.AlterField(
            model_name='post',
            name='endPeriod',
            field=models.DateField(verbose_name='여행끝'),
        ),
        migrations.AlterField(
            model_name='post',
            name='record',
            field=models.TextField(verbose_name='여행기록'),
        ),
        migrations.AlterField(
            model_name='post',
            name='startPeriod',
            field=models.DateField(verbose_name='여행시작'),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=20, verbose_name='제목'),
        ),
    ]
