# Generated by Django 4.2.1 on 2023-07-15 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_post_is_public'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='latitude',
            field=models.FloatField(default=37.566826),
        ),
        migrations.AddField(
            model_name='post',
            name='longitude',
            field=models.FloatField(default=126.9786567),
        ),
    ]
