# Generated by Django 4.2.1 on 2023-07-15 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_post_latitude_post_longitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='latitude',
            field=models.FloatField(blank=True, default=37.566826, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='longitude',
            field=models.FloatField(blank=True, default=126.9786567, null=True),
        ),
    ]
